### PR TITLE
Update for MOI 0.9 and JuMP 0.20

### PR DESCRIPTION
**Pull request by guilhermebodin**
This should work once SCS supports DualExponentialCones

### CODE REVIEW

**Comment by guilhermebodin** [comment]
One thing that did not work as I thought is that I had to do a small change in lots of tests. Maybe we should change a little the design of these tests for easier integration in the future.

**Comment by guilhermebodin** [comment]
Once these are merged https://github.com/JuliaOpt/MathOptInterface.jl/pull/873 https://github.com/JuliaOpt/SCS.jl/pull/155 we should get back with exponential cone tests

**Comment by guilhermebodin** [comment]
travis is failing because CSDP is terminating with `SLOWPROGRESS`. 
image

Don't know exactly what is causing this.

**Comment by blegat** [comment]
CSDP happens to end with SLOW_PROGRESS on simple tests. If you look at `CSDP/test/runtests` you'll see that some tests are excluded. You can exclude the failing CSDP test.

**Pull request merged**
